[Service]
Host = "localhost"
Port = 49990
ConnectRetries = 3
HealthCheck = ""
Labels = []
OpenMsg = "device simple started"
ReadMaxLimit = 256
Timeout = 5000

[Registry]
Host = "localhost"
Port = 8500

[Clients]
  [Clients.Data]
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Host = "localhost"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Host = "localhost"
  Port = 48061
  Timeout = 50000

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
File = "./device-simple.log"

