[Service]
Host = "localhost"
Port = 49990
ConnectRetries = 3
HealthCheck = ""
Labels = []
OpenMsg = "device simple started"
ReadMaxLimit = 256
Timeout = 5000

[Registry]
Host = "localhost"
Port = 8500

[Clients]
  [Data]
  Host = "localhost"
  Port = 48080

  [Metadata]
  Host = "localhost"
  Port = 48081

[Devices]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./profiles"
  SendReadingsOnChanged = true

[Logging]
RemoteURL = ''
File = "./device-simple.log"

