version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/edgexfoundry/go-mod-core-contracts/v4"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-messaging/v4"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-registry/v4"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-secrets/v4"
        # Included when go-mod-bootstrap is updated